### ISSUE TITLE
Linux install problems.

### ISSUE THREAD

**Issue by mocallins** [tcl-dp/tcl-dp#6]
Should TCL-DP run build/run on a Debian based linux distro, more specifically Raspbian ?

I seem to have issues with cmake failing not being able to find things.

**Comment by mfld-fr** [comment]
Hello @mocallins, this version builds on Windows (manually) and Ubuntu (automatic). For the latest, I had to insert a setup step in https://github.com/tcl-dp/tcl-dp/blob/master/.github/workflows/build.yml:
```
    - name: Setup
      run: sudo apt-get install tcl-dev
```

Could you please copy / paste here the CMake finding failures, to get a more precise idea of the problem you are facing ?

Edit : also just tested on my Gentoo, build completed without any trouble.

**Comment by mocallins** [comment]
I also noticed you suggested apt-get tcl-dev, i had thought about that a well, but i  did aprt-get tcl8.6-dev.
But when i rereaan to get the output, i did that first too.
I also went throught a bunch of iterations with the -DTCL-HOME variable, trying to sdee if i could decipher what it was looking for, where, and never could get it nailed down.
Here;s the output:
cmake ..
Checking Tcl location TCL_HOME='/usr' specified by the user.
-- Could NOT find TCLTK (missing: TK_INCLUDE_PATH)
-- Could NOT find TK (missing: TK_INCLUDE_PATH)
dp does not use Tk, so you can ignore the above 'Could NOT find TK' messages.
Checking to make sure the Tcl found is within the user-specified TCL_HOME.
According to FindTCL TCL_LIBRARY, using the Tcl installed within '/usr/lib'.
According to FindTCL TCL_TCLSH, using the Tcl installed within '/usr'.
According to FindTclStub TCL_STUB_LIBRARY, using the Tcl installed within '/usr/lib'.
As a workaround to CMake bug 11033, you must create symbolic links in TCL_HOME.
For example, suppose you had specified TCL_HOME=/home/voom/tcl8.4.19:
  cd /home/voom/tcl8.4.19/lib
  ln -s libtcl8.4.so libtcl.so
  ln -s libtclstub8.4.a libtclstub.a
  cd /home/voom/tcl8.4.19/bin
  ln -s tclsh8.4 tclsh
CMake Error at CMakeLists.txt:102 (message):
  See http://www.cmake.org/Bug/view.php?id=11033 for details.


-- Configuring incomplete, errors occurred!
See also "/home/pi/build/tcldp-4.2.0/build/CMakeFiles/CMakeOutput.log".

Also perhaps you've expected some determined locations, but trying to follow your example, "if installed in a different location", which i am not.The tcl executble is not in the same locations, nor the libraries in subdirectories, of that location.Which is why i was wondering if its a distro thing or something.



    On Sunday, December 18, 2022 at 01:19:15 PM CST, MFLD ***@***.***> wrote:  
 
 


Hello @mocallins, this version builds on Windows (manually) and Ubuntu (automatic). For the latest, I had to insert a setup step in https://github.com/tcl-dp/tcl-dp/blob/master/.github/workflows/build.yml:
    - name: Setup
      run: sudo apt-get install tcl-dev

Could you please copy / paste here the CMake finding failures, to get a more precise idea of the problem you are facing ?

**Comment by mocallins** [comment]
Ok 

> Hello @mocallins, this version builds on Windows (manually) and Ubuntu (automatic). For the latest, I had to insert a setup step in https://github.com/tcl-dp/tcl-dp/blob/master/.github/workflows/build.yml:
> 
> ```
>     - name: Setup
>       run: sudo apt-get install tcl-dev
> ```
> 
> Could you please copy / paste here the CMake finding failures, to get a more precise idea of the problem you are facing ?
> 
> Edit : also just tested on my Gentoo, build completed without any trouble.

Ok, got it to build and install
I notced in the readme about the workflows,, so i went and checked my copy, and it didn't have that.
So i re-downloaded the whole thing.

It built and installed no problem.

**Comment by mocallins** [comment]
New download installed
