### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by mperham** [tcl-dp/tcl-dp#7]
I worked on Tcl-DP in 1996-97 as an undergrad in Brian Smith's lab at Cornell. Amazing to see it still being maintained and enhanced. Here's my old homepage with a mention.

https://perham.net/mike/cornell/

Incredible. Cheers!

**Comment by mperham** [comment]
https://perham.net/mike/cornell/dp97.html

**Comment by mfld-fr** [comment]
Hello @mperham, nice to meet you!

Tcl-DP is still used in my company to drive a legacy test bench through some Tcl/Tk scripts, so the contribution to keep that project alive and be able to upgrade our scripts.
